sonar.projectKey=dydymerho_EV-Co-ownership-Cost-sharing-System-Test
sonar.organization=dydymerho
sonar.sources=.
sonar.host.url=https://sonarcloud.io

# Quan trọng: Chỉ định tất cả file .java đều nằm trong tầm quét
sonar.java.binaries=.
# Nếu bạn muốn quét sâu hơn, hãy liệt kê các folder microservice của bạn tại đây
# sonar.sources=service-1/src/main/java,service-2/src/main/java
