# Port configuration
server.port=8083

# MySQL Database connection (Docker)
spring.datasource.url=jdbc:mysql://user-mysql:3306/CoOwnershipDB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Secret Key
jwt.secret.key=RjlaYTRjY2RmYS04NjcwLTRkMDMtYmI1OS02ZmMxNmIzNjAwYmY=

# Multipart configuration for KYC uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=45MB

# Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
